// chat/components/stack/map-node.tsx
"use client";

import { ChevronDown } from "lucide-react";
import { useState } from "react";
import { cn } from "@/lib/utils";
import { Sparkline } from "./sparkline";
import { STATUS_LABEL, STATUS_VAR, type StackNode } from "./types";

const compact = new Intl.NumberFormat("en", { notation: "compact" });

export function MapNode({
  node,
  pulsed,
  trailed,
  nodeRef,
}: {
  node: StackNode;
  pulsed?: boolean;
  // Persistent "show on map" / safety-event highlight. Driven by React state in
  // StackMap (not an imperative classList) so it survives the re-render an
  // incoming chat message triggers — that re-render was wiping the old class.
  trailed?: boolean;
  nodeRef?: (el: HTMLButtonElement | null) => void;
}) {
  const [open, setOpen] = useState(false);
  const isWanted = node.st === "wanted";
  const color = STATUS_VAR[node.st];
  const atlas = node.atlas;

  return (
    <button
      className={cn(
        "group relative flex flex-1 basis-[200px] flex-col select-text rounded-[10px] border-[1.5px] px-[15px] py-[10px] text-left transition-[border-color,box-shadow] duration-150",
        isWanted
          ? "border-dashed bg-transparent"
          : "border-[var(--ap-rule)] bg-[var(--ap-paper)]",
        // Both "running this turn" (pulsed) and "show on map / safety event"
        // (trailed) use the SAME calm green wash — no animate-pulse, no coral.
        // (The old pulsed path flashed fast + red; "running" is signalled by
        // the header dot, the node just gets the quiet highlight.)
        (pulsed || trailed) && "ap-trail"
      )}
      onClick={() => setOpen((o) => !o)}
      ref={nodeRef}
      style={{
        minWidth: 185,
        borderLeft: `4px ${isWanted ? "dashed" : "solid"} ${color}`,
        ...(isWanted
          ? { borderColor: "var(--ap-ink-3)", borderLeftColor: color }
          : {}),
      }}
      type="button"
    >
      <div className="flex items-start justify-between gap-2">
        <div className="min-w-0">
          <div className="flex items-center gap-2 font-medium text-[14px] text-[var(--ap-ink)]">
            <span
              className="size-[9px] shrink-0 rounded-full"
              style={
                isWanted
                  ? {
                      background: "transparent",
                      border: "1.5px solid var(--ap-ink-3)",
                    }
                  : { background: color }
              }
            />
            <span className="truncate">{node.nm}</span>
          </div>
          <div className="mt-0.5 truncate text-[12px] text-[var(--ap-ink-3)]">
            {node.org}
          </div>
        </div>
        <span
          className="shrink-0 font-mono text-[10px] uppercase tracking-[0.14em]"
          style={{ color: isWanted ? "var(--ap-coral)" : color }}
        >
          {STATUS_LABEL[node.st]}
        </span>
      </div>

      <div className="mt-1.5 text-[11.5px] text-[var(--ap-ink-2)] leading-snug">
        {node.d}
      </div>

      {/* Subtle "expandable" affordance — clarifies the card is clickable to
          inspect; strengthens on hover, flips when open. */}
      <ChevronDown
        aria-hidden="true"
        className={cn(
          "pointer-events-none absolute right-2 bottom-2 size-3 text-[var(--ap-ink-3)] opacity-25 transition-[transform,opacity] duration-200 group-hover:opacity-70",
          open && "rotate-180 opacity-50"
        )}
      />

      {open && (
        <div className="mt-2 border-[var(--ap-rule)] border-t border-dashed pt-2">
          {atlas ? (
            <div className="space-y-1">
              <div className="flex items-center gap-2 font-mono text-[10px] text-[var(--ap-ink-3)]">
                <span>
                  ★ {atlas.stars != null ? compact.format(atlas.stars) : "—"}
                  {atlas.stars7d
                    ? ` (+${compact.format(atlas.stars7d)}/wk)`
                    : ""}
                </span>
                {atlas.sparkline && <Sparkline values={atlas.sparkline} />}
              </div>
              <div className="font-mono text-[10px] text-[var(--ap-ink-3)] leading-[1.7]">
                {atlas.contributors != null && (
                  <span>
                    {compact.format(atlas.contributors)} contributors ·{" "}
                  </span>
                )}
                {atlas.language && <span>{atlas.language} · </span>}
                {atlas.commits90d != null && (
                  <span>{compact.format(atlas.commits90d)} commits/90d · </span>
                )}
                <span>{atlas.openness}</span>
                {atlas.license ? <span> · {atlas.license}</span> : null}
              </div>
              <div className="font-mono text-[10px] text-[var(--ap-ink-3)]">
                via OSO product-view
              </div>
            </div>
          ) : (
            <div className="font-mono text-[10px] text-[var(--ap-ink-3)] leading-[1.7]">
              {isWanted
                ? "open projects exist for this"
                : (node.prov ?? "provenance on the live stack")}
            </div>
          )}
          {node.lineage && (
            <div className="mt-2 space-y-1 border-[var(--ap-rule)] border-t border-dashed pt-2">
              <div className="font-mono text-[10px] text-[var(--ap-ink-2)]">
                training data — {node.lineage.summary}
              </div>
              {node.lineage.facts?.length ? (
                <ul className="font-mono text-[10px] text-[var(--ap-ink-3)] leading-[1.7]">
                  {node.lineage.facts.map((f) => (
                    <li key={f}>· {f}</li>
                  ))}
                </ul>
              ) : null}
              {node.lineage.links?.length ? (
                <div className="flex flex-wrap gap-3 font-mono text-[10px]">
                  {node.lineage.links.map((l) => (
                    <a
                      className="text-[var(--ap-coral)] underline-offset-2 hover:underline"
                      href={l.url}
                      key={l.url}
                      onClick={(e) => e.stopPropagation()}
                      rel="noreferrer"
                      target="_blank"
                    >
                      {l.label}
                    </a>
                  ))}
                </div>
              ) : null}
            </div>
          )}
          <div className="mt-2 flex gap-3 font-mono text-[10px]">
            {(atlas?.url ?? node.url) && (
              <a
                className="text-[var(--ap-ink-2)] underline-offset-2 hover:underline"
                href={atlas?.url ?? node.url}
                onClick={(e) => e.stopPropagation()}
                rel="noreferrer"
                target="_blank"
              >
                {node.url && !atlas ? "Open weights ↗" : "GitHub ↗"}
              </a>
            )}
            {(isWanted || node.st === "gap") && (
              <a
                className="font-semibold text-[var(--ap-coral)] underline-offset-2 hover:underline"
                href={`mailto:contact@aipotluck.org?subject=${encodeURIComponent(
                  `Get involved: ${node.nm}`
                )}`}
                onClick={(e) => e.stopPropagation()}
              >
                Get involved →
              </a>
            )}
          </div>
        </div>
      )}
    </button>
  );
}

// chat-svelte/src/lib/components/stack/MapNode.svelte
<script lang="ts">
	import ChevronDown from "~icons/lucide/chevron-down";
	import Sparkline from "./Sparkline.svelte";
	import { STATUS_LABEL, STATUS_VAR, type StackNode } from "./types";

	interface Props {
		node: StackNode;
		// Pulsed while this node's turn streams; trailed = a persisted "show on
		// map" / safety highlight. Both render the same calm green wash (.ap-trail).
		pulsed?: boolean;
		trailed?: boolean;
	}
	let { node, pulsed = false, trailed = false }: Props = $props();

	const compact = new Intl.NumberFormat("en", { notation: "compact" });
	const fmt = (n: number | null | undefined) => (n != null ? compact.format(n) : "—");

	let open = $state(false);

	let isWanted = $derived(node.st === "wanted");
	let color = $derived(STATUS_VAR[node.st]);
	let atlas = $derived(node.atlas);

	let buttonClass = $derived(
		[
			"group relative flex flex-1 basis-[200px] flex-col select-text rounded-[10px] border-[1.5px] px-[15px] py-[10px] text-left transition-[border-color,box-shadow] duration-150",
			isWanted ? "border-dashed bg-transparent" : "border-[var(--ap-rule)] bg-[var(--ap-paper)]",
			pulsed || trailed ? "ap-trail" : "",
		].join(" ")
	);

	// Left accent border carries the status colour; wanted nodes get a dashed
	// outline with the status colour only on the left edge.
	let buttonStyle = $derived(
		`min-width:185px;border-left:4px ${isWanted ? "dashed" : "solid"} ${color};` +
			(isWanted ? `border-color:var(--ap-ink-3);border-left-color:${color};` : "")
	);
</script>

<button
	type="button"
	class={buttonClass}
	style={buttonStyle}
	data-node-id={node.id}
	onclick={() => (open = !open)}
>
	<div class="flex items-start justify-between gap-2">
		<div class="min-w-0">
			<div class="flex items-center gap-2 text-[14px] font-medium text-[var(--ap-ink)]">
				<span
					class="size-[9px] shrink-0 rounded-full"
					style={isWanted
						? "background:transparent;border:1.5px solid var(--ap-ink-3);"
						: `background:${color};`}
				></span>
				<span class="truncate">{node.nm}</span>
			</div>
			<div class="mt-0.5 truncate text-[12px] text-[var(--ap-ink-3)]">{node.org}</div>
		</div>
		<span
			class="shrink-0 font-mono text-[10px] tracking-[0.14em] uppercase"
			style="color:{isWanted ? 'var(--ap-coral)' : color};"
		>
			{STATUS_LABEL[node.st]}
		</span>
	</div>

	<div class="mt-1.5 text-[11.5px] leading-snug text-[var(--ap-ink-2)]">{node.d}</div>

	<!-- Subtle "expandable" affordance — strengthens on hover, flips when open. -->
	<ChevronDown
		aria-hidden="true"
		class="pointer-events-none absolute right-2 bottom-2 size-3 text-[var(--ap-ink-3)] opacity-25 transition-[transform,opacity] duration-200 group-hover:opacity-70 {open
			? 'rotate-180 opacity-50'
			: ''}"
	/>

	{#if open}
		<div class="mt-2 border-t border-dashed border-[var(--ap-rule)] pt-2">
			{#if atlas}
				<div class="space-y-1">
					<div class="flex items-center gap-2 font-mono text-[10px] text-[var(--ap-ink-3)]">
						<span>
							★ {fmt(atlas.stars)}{atlas.stars7d ? ` (+${compact.format(atlas.stars7d)}/wk)` : ""}
						</span>
						{#if atlas.sparkline}
							<Sparkline values={atlas.sparkline} />
						{/if}
					</div>
					<div class="font-mono text-[10px] leading-[1.7] text-[var(--ap-ink-3)]">
						{#if atlas.contributors != null}<span>{compact.format(atlas.contributors)} contributors · </span>{/if}
						{#if atlas.language}<span>{atlas.language} · </span>{/if}
						{#if atlas.commits90d != null}<span>{compact.format(atlas.commits90d)} commits/90d · </span>{/if}
						<span>{atlas.openness}</span>
						{#if atlas.license}<span> · {atlas.license}</span>{/if}
					</div>
					<div class="font-mono text-[10px] text-[var(--ap-ink-3)]">via OSO product-view</div>
				</div>
			{:else}
				<div class="font-mono text-[10px] leading-[1.7] text-[var(--ap-ink-3)]">
					{isWanted ? "open projects exist for this" : (node.prov ?? "provenance on the live stack")}
				</div>
			{/if}

			{#if node.lineage}
				<div class="mt-2 space-y-1 border-t border-dashed border-[var(--ap-rule)] pt-2">
					<div class="font-mono text-[10px] text-[var(--ap-ink-2)]">
						training data — {node.lineage.summary}
					</div>
					{#if node.lineage.facts?.length}
						<ul class="font-mono text-[10px] leading-[1.7] text-[var(--ap-ink-3)]">
							{#each node.lineage.facts as f}
								<li>· {f}</li>
							{/each}
						</ul>
					{/if}
					{#if node.lineage.links?.length}
						<div class="flex flex-wrap gap-3 font-mono text-[10px]">
							{#each node.lineage.links as l}
								<a
									class="text-[var(--ap-coral)] underline-offset-2 hover:underline"
									href={l.url}
									onclick={(e) => e.stopPropagation()}
									rel="noreferrer"
									target="_blank">{l.label}</a
								>
							{/each}
						</div>
					{/if}
				</div>
			{/if}

			<div class="mt-2 flex gap-3 font-mono text-[10px]">
				{#if atlas?.url ?? node.url}
					<a
						class="text-[var(--ap-ink-2)] underline-offset-2 hover:underline"
						href={atlas?.url ?? node.url}
						onclick={(e) => e.stopPropagation()}
						rel="noreferrer"
						target="_blank">{node.url && !atlas ? "Open weights ↗" : "GitHub ↗"}</a
					>
				{/if}
				{#if isWanted || node.st === "gap"}
					<a
						class="font-semibold text-[var(--ap-coral)] underline-offset-2 hover:underline"
						href="mailto:contact@aipotluck.org?subject={encodeURIComponent(
							`Get involved: ${node.nm}`
						)}"
						onclick={(e) => e.stopPropagation()}>Get involved →</a
					>
				{/if}
			</div>
		</div>
	{/if}
</button>
