// app/src/components/explorer/Sparkline.jsx
export function Sparkline({ data, width = 80, height = 24, color = 'rgba(255,255,255,.5)', filled = false }) {
  if (!data || data.length === 0) {
    return (
      <svg width={width} height={height} viewBox={`0 0 ${width} ${height}`}>
        <line x1={0} y1={height / 2} x2={width} y2={height / 2}
          stroke="rgba(255,255,255,.12)" strokeWidth={1} strokeDasharray="2,3" />
      </svg>
    );
  }

  const max = Math.max(...data, 1);
  const min = Math.min(...data, 0);
  const range = max - min || 1;
  const padY = 2;
  const usableHeight = height - padY * 2;

  const points = data.map((v, i) => {
    const x = (i / (data.length - 1)) * width;
    const y = padY + usableHeight - ((v - min) / range) * usableHeight;
    return `${x},${y}`;
  });

  const pathD = `M${points.join(' L')}`;
  const fillD = `${pathD} L${width},${height} L0,${height} Z`;

  return (
    <svg width={width} height={height} viewBox={`0 0 ${width} ${height}`}>
      {filled && (
        <path d={fillD} fill={color} opacity={0.12} />
      )}
      <path d={pathD} fill="none" stroke={color} strokeWidth={1.5}
        strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  );
}

// chat-svelte/src/lib/components/stack/Sparkline.svelte
<script lang="ts">
	// Tiny inline activity sparkline (real star history from the OSO catalog).
	// Ported from the Next chat/ app (components/stack/sparkline.tsx).
	interface Props {
		values: number[];
		width?: number;
		height?: number;
	}
	let { values, width = 96, height = 20 }: Props = $props();

	const points = $derived.by(() => {
		if (!values || values.length < 2) return null;
		const max = Math.max(...values, 1);
		const min = Math.min(...values, 0);
		const span = max - min || 1;
		const step = width / (values.length - 1);
		return values
			.map((v, i) => {
				const x = i * step;
				const y = height - ((v - min) / span) * (height - 2) - 1;
				return `${x.toFixed(1)},${y.toFixed(1)}`;
			})
			.join(" ");
	});
</script>

{#if points}
	<svg aria-hidden="true" class="overflow-visible" {height} viewBox="0 0 {width} {height}" {width}>
		<polyline
			fill="none"
			{points}
			stroke="var(--ap-live)"
			stroke-linecap="round"
			stroke-linejoin="round"
			stroke-width="1.5"
		/>
	</svg>
{/if}
