// chat/components/stack/sparkline.tsx
// Tiny inline activity sparkline (real star history from OSO sparklines.json).
export function Sparkline({
  values,
  width = 96,
  height = 20,
}: {
  values: number[];
  width?: number;
  height?: number;
}) {
  if (!values || values.length < 2) {
    return null;
  }
  const max = Math.max(...values, 1);
  const min = Math.min(...values, 0);
  const span = max - min || 1;
  const step = width / (values.length - 1);
  const pts = values.map((v, i) => {
    const x = i * step;
    const y = height - ((v - min) / span) * (height - 2) - 1;
    return `${x.toFixed(1)},${y.toFixed(1)}`;
  });
  return (
    <svg
      aria-hidden="true"
      className="overflow-visible"
      height={height}
      viewBox={`0 0 ${width} ${height}`}
      width={width}
    >
      <polyline
        fill="none"
        points={pts.join(" ")}
        stroke="var(--ap-live)"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

// chat-svelte/src/lib/components/stack/Sparkline.svelte
<script lang="ts">
	// Tiny inline activity sparkline (real star history from the OSO catalog).
	// Ported from the Next chat/ app (components/stack/sparkline.tsx).
	interface Props {
		values: number[];
		width?: number;
		height?: number;
	}
	let { values, width = 96, height = 20 }: Props = $props();

	const points = $derived.by(() => {
		if (!values || values.length < 2) return null;
		const max = Math.max(...values, 1);
		const min = Math.min(...values, 0);
		const span = max - min || 1;
		const step = width / (values.length - 1);
		return values
			.map((v, i) => {
				const x = i * step;
				const y = height - ((v - min) / span) * (height - 2) - 1;
				return `${x.toFixed(1)},${y.toFixed(1)}`;
			})
			.join(" ");
	});
</script>

{#if points}
	<svg aria-hidden="true" class="overflow-visible" {height} viewBox="0 0 {width} {height}" {width}>
		<polyline
			fill="none"
			{points}
			stroke="var(--ap-live)"
			stroke-linecap="round"
			stroke-linejoin="round"
			stroke-width="1.5"
		/>
	</svg>
{/if}
